export const CHANGE_INPUTFIELD = 'CHANGE_INPUTFIELD';
export const REQUEST_PRODUCTS_PENDING = 'REQUEST_PRODUCTS_PENDING';
export const REQUEST_PRODUCTS_SUCCESS = 'REQUEST_PRODUCTS_SUCCESS';
export const REQUEST_PRODUCTS_REJECTED = 'REQUEST_PRODUCTS_REJECTED';