export const CHANGE_INPUTFIELD = 'CHANGE_INPUTFIELD';
export const REQUEST_PRODUCTS_PENDING = 'REQUEST_PRODUCTS_PENDING';
export const REQUEST_PRODUCTS_SUCCESS = 'REQUEST_PRODUCTS_SUCCESS';
export const REQUEST_PRODUCTS_REJECTED = 'REQUEST_PRODUCTS_REJECTED';
export const SELECT_PRODUCTS_BY_CATEGORY = "SELECT_PRODUCTS_BY_CATEGORY";
export const RESTORE_PRODUCTS = "RESTORE_PRODUCTS";
export const ORDER_PRODUCTS = "ORDER_PRODUCTS";